### ISSUE TITLE
Possible to get a list of changes in CRAN version (8.4)?

### ISSUE THREAD

**Issue by bzki** [NCAR/LatticeKrig#1]
Thanks for the excellent package.

I was not sure if this is an appropriate place to bring up questions, issues or requests. If not, I can delete this. 

Currently the CRAN page does not have much information on version releases outside of some description of the package since 5.4: for example, see [the CRAN NEWS page for dplyr](https://cran.r-project.org/web/packages/dplyr/news/news.html). I am not an expert in package development but there is some information about managing packages in Github and CRAN [here in the R Packages chapter](http://r-pkgs.had.co.nz/release.html). My immediate question is: What are the main changes in the most recent version on CRAN (8.4) vs. 7.0? Are there any substantial changes to functions that would break existing code upon updating the package?

**Comment by dnychka** [comment]
Who are you?

Douglas Nychka
Personal email
Cell 3037253199
